apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-csharp-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myappcsharp
  template:
    metadata:
      labels:
        app: myappcsharp
    spec:
      containers:
      - name: myappcsharp
        image: hanryos/appcsharp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
